//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class heroBoard
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="A Name is required")]
        public string Name { get; set; }

        [Required(ErrorMessage ="A Class is required")]
        public string Class { get; set; }

        [Required(ErrorMessage ="A brief description is required")]
        public string Description { get; set; }


        [Required(ErrorMessage ="A difficulty level is required")]
        [Range(1,3, ErrorMessage ="Please choose a difficulty between 1 and 3")]
        public int Difficulty { get; set; }
 
        [Required(ErrorMessage ="A Story about the Hero is Required")]
        public string Story { get; set; }

        [Required(ErrorMessage ="A URL address for this hero's image if required. If you have no image, please type 'none'")]
        public string Picture { get; set; }
    }
}
